PLUGIN_NAME=		nacmanager
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		NAC Manager companion for FreeRADIUS MAC authentication
PLUGIN_DEPENDS=		freeradius3
PLUGIN_MAINTAINER=	local

.include "../../Mk/plugins.mk"
